import Link from "next/link";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { createClient } from "@/lib/supabase/server";
import { analyzeRoutine, type RoutineExercise } from "@/lib/muscle-analysis";
import {
  generateWeeklyPlan,
  type ExerciseCandidate,
  type WeeklyPlan,
} from "@/lib/plan-generator";

import { PlanEditor } from "./plan-editor";

type ProfileRow = {
  available_days: number[] | null;
  experience_level: string | null;
  available_equipment: string[] | null;
  primary_goal: string | null;
};

type RoutineRow = {
  exercise_id: number | string;
  sets: number | string | null;
  reps: number | string | null;
  weight: number | string | null;
  day_of_week: number | string | null;
  exercises: {
    name: string | null;
    primary_muscle: string | null;
    secondary_muscles: string[] | null;
    equipment: string | null;
    difficulty: string | null;
  } | null;
};

function safeNumber(n: unknown, fallback = 0) {
  const x = typeof n === "number" ? n : Number(n);
  return Number.isFinite(x) ? x : fallback;
}

function normalizeToken(s: unknown) {
  if (typeof s !== "string") return "";
  return s.trim().toLowerCase().replace(/\s+/g, " ");
}

function equipmentAllowedSet(tags: string[]) {
  const t = new Set(tags.map(normalizeToken));
  if (t.has(normalizeToken("Full gym access"))) return null; // null => allow all
  const allowed = new Set<string>();
  if (t.has(normalizeToken("Dumbbells"))) allowed.add("dumbbell");
  if (t.has(normalizeToken("Barbell and plates"))) allowed.add("barbell");
  if (t.has(normalizeToken("Resistance bands"))) allowed.add("bands");
  if (t.has(normalizeToken("Bodyweight only"))) allowed.add("body only");
  return allowed;
}

function extractImbalanceMuscles(analysis: ReturnType<typeof analyzeRoutine>) {
  // Heuristic: parse muscle names from imbalance titles generated by our engine.
  // Examples:
  // - "Low chest volume" -> chest
  // - "Chest not trained" -> chest
  const muscles = new Set<string>();
  for (const imb of analysis.imbalances) {
    const title = imb.title.toLowerCase();
    const lowMatch = title.match(/^low (.+) volume$/);
    if (lowMatch?.[1]) muscles.add(lowMatch[1]);
    const notTrainedMatch = title.match(/^(.+) not trained$/);
    if (notTrainedMatch?.[1]) muscles.add(notTrainedMatch[1]);
  }
  return Array.from(muscles);
}

function dayLabel(d: number) {
  const map: Record<number, string> = {
    1: "Mon",
    2: "Tue",
    3: "Wed",
    4: "Thu",
    5: "Fri",
    6: "Sat",
    7: "Sun",
  };
  return map[d] ?? String(d);
}

export async function PlanView() {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    // Page shell should have redirected already, but be safe.
    return null;
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("available_days, experience_level, available_equipment, primary_goal")
    .eq("id", user.id)
    .single();

  const p = (profile ?? null) as unknown as ProfileRow | null;
  const availableDays =
    Array.isArray(p?.available_days) && p!.available_days.length > 0
      ? p!.available_days
      : [1, 2, 3, 4, 5];
  const usedDefaultDays =
    !Array.isArray(p?.available_days) || (p?.available_days?.length ?? 0) === 0;

  const experience = p?.experience_level ?? "Beginner (less than 6 months)";
  const availableEquipment = Array.isArray(p?.available_equipment) ? p!.available_equipment : [];

  const { data: activePlan } = await supabase
    .from("plans")
    .select("id, name")
    .eq("user_id", user.id)
    .eq("is_active", true)
    .maybeSingle();

  const { data: routineJoin } = activePlan
    ? await supabase
        .from("routines")
        .select(
          "exercise_id, sets, reps, weight, day_of_week, exercises(name, primary_muscle, secondary_muscles, equipment, difficulty)",
        )
        .eq("plan_id", activePlan.id)
    : { data: [] as unknown[] };

  const rows = (routineJoin ?? []) as unknown as RoutineRow[];
  if (rows.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Your plan is ready once we know your routine</CardTitle>
          <CardDescription>
            Set up your current routine first so we can generate a personalized plan.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Button asChild variant="outline">
            <Link href="/plans">Create a plan</Link>
          </Button>
        </CardContent>
      </Card>
    );
  }

  const routine: RoutineExercise[] = rows
    .map((r) => {
      const ex = r.exercises;
      return {
        exercise_id: safeNumber(r.exercise_id),
        name: ex?.name ?? "Unknown exercise",
        primary_muscle: ex?.primary_muscle ?? "",
        secondary_muscles: ex?.secondary_muscles ?? [],
        sets: safeNumber(r.sets),
        reps: safeNumber(r.reps),
        weight: safeNumber(r.weight),
        day_of_week: safeNumber(r.day_of_week),
      };
    })
    .filter((x) => x.exercise_id > 0 && x.sets > 0);

  const analysis = analyzeRoutine(routine);
  const imbalanceMuscles = extractImbalanceMuscles(analysis);

  const allowed = equipmentAllowedSet(availableEquipment);

  // Fetch a medium-sized exercise library for generation.
  // If "full gym", no equipment filter; otherwise constrain to allowed equipment and include nulls.
  let libQuery = supabase
    .from("exercises")
    .select("id, name, primary_muscle, secondary_muscles, equipment, difficulty")
    .limit(200);

  if (allowed && allowed.size > 0) {
    const allowedArr = Array.from(allowed);
    libQuery = libQuery.or(`equipment.in.(${allowedArr.join(",")}),equipment.is.null`);
  }

  const { data: libRows } = await libQuery;

  const exerciseLibrary: ExerciseCandidate[] = (libRows ?? []).map((r: any) => ({
    id: Number(r.id),
    name: String(r.name),
    primary_muscle: String(r.primary_muscle ?? ""),
    secondary_muscles: Array.isArray(r.secondary_muscles) ? r.secondary_muscles : [],
    equipment: r.equipment ?? null,
    difficulty: String(r.difficulty ?? ""),
  }));

  const plan: WeeklyPlan = generateWeeklyPlan({
    availableDays,
    experience,
    availableEquipment,
    exerciseLibrary,
    weeklyVolume: analysis.weeklyVolume,
    imbalanceMuscles,
    primaryGoal: p?.primary_goal ?? undefined,
  });

  return (
    <div className="space-y-4">
      <div className="space-y-3">
        {usedDefaultDays && (
          <div className="rounded-lg border-l-2 border-l-lime-400 border border-zinc-800 bg-zinc-900 p-3 text-sm text-zinc-300">
            We didn&apos;t find schedule days on your profile, so we defaulted to{" "}
            <span className="font-medium">Mon–Fri</span>. You can update this in onboarding.
          </div>
        )}

        {plan.notes.length > 0 && (
          <div className="space-y-2">
            {plan.notes.map((n, idx) => (
              <div
                key={`${idx}-${n}`}
                className="rounded-lg border-l-2 border-l-lime-400 border border-zinc-800 bg-zinc-900 p-3 text-sm text-zinc-300"
              >
                {n}
              </div>
            ))}
          </div>
        )}

        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="secondary">Days: {availableDays.map(dayLabel).join(", ")}</Badge>
          <Badge variant="secondary">Experience: {experience}</Badge>
          {availableEquipment.length > 0 && (
            <Badge variant="secondary">
              Equipment: {availableEquipment.join(", ")}
            </Badge>
          )}
        </div>
      </div>

      <PlanEditor initialPlan={plan} initialAvailableDays={availableDays} />
    </div>
  );
}

